CREATE TABLE "docs" (
	"id"	INTEGER NOT NULL UNIQUE,
	"state"	INTEGER NOT NULL,
	PRIMARY KEY("id")
);

CREATE TABLE "users" (
	"id"	INTEGER NOT NULL UNIQUE,
	PRIMARY KEY("id")
);

CREATE TABLE "stateLog" (
	"id"	INTEGER NOT NULL UNIQUE,
	"changeTime"	INTEGER NOT NULL,
	"oldState"	INTEGER,
	"newState"	INTEGER NOT NULL CHECK("newState" != "oldState"),
	"docId"	INTEGER NOT NULL,
	"userId"	INTEGER NOT NULL,
	FOREIGN KEY("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY("docId") REFERENCES "docs"("id") ON DELETE CASCADE ON UPDATE CASCADE,
	PRIMARY KEY("id")
);